[feature/chucker-gql] GQL support against latest develop
ChuckerTeam/chucker pull request #800
Opened 2022-04-18 08:17 UTC by alkber

There was already an old implementation done [here ](https://github.com/ChuckerTeam/chucker/pull/70). This PR seems to be old one (2019) and way out of sync with develop branch. I have refactored it to meet the latest changes. 

This almost getting ready and not the final PR yet, need to get valuable input on the code quality and optimization if required. 

Sample Activity has also been provided for the demo

**Known Issues**  
Couldn't successfully run the sample until i commented this part of the code 

```
//        StrictMode.setVmPolicy(
//            StrictMode.VmPolicy.Builder()
//                .detectLeakedClosableObjects()
//                .penaltyLog()
//                .penaltyDeath()
//                .build()
//        )
//
//        StrictMode.setThreadPolicy(
//            StrictMode.ThreadPolicy.Builder()
//                .detectDiskReads()
//                .detectDiskWrites()
//                .penaltyLog()
//                .penaltyDeath()
//                .build()
//        )
```

2022-04-18 11:29 UTC, MiSikora requested changes
For a PR that introduces integration with a new specification, there are no tests. Please cover necessary scenarios such as GET and POST requests with `ChuckerInterceptor` as both application and network interceptor.

It would be also helpful if you could follow our PR template. Screenshots especially would be appreciated.

2022-04-18 11:29 UTC, MiSikora commented on sample/src/main/kotlin/com/chuckerteam/chucker/sample/GqlHttpTask.kt
> +    private val api = Retrofit.Builder()
I think that the vast majority of people will use GraphQL with something like Apollo. I would prefer to see a real-life scenario integration within our sample.

2022-04-18 11:29 UTC, MiSikora commented on library/src/main/kotlin/com/chuckerteam/chucker/internal/support/RequestProcessor.kt
> +    private fun inferGqlRequest(body: String): String? {
Inferring GraphQL from a body won't work for GET requests as there is only URL query parameter for those.

It's a bit hard to have a full-proof solution as anyone could have query parameters or bodies that conform to GraphQL format. I have an idea of how to deal with it but let's just first implement handling of GET requests as well.

2022-04-18 11:29 UTC, MiSikora commented on library/src/main/kotlin/com/chuckerteam/chucker/internal/data/entity/HttpTransaction.kt
> +        get() = !gqlOperationName.isNullOrEmpty()
This doesn't seem right. The `operationName` is an optional parameter in [GraphQL](https://graphql.org/learn/serving-over-http/#post-request). I think we can rely solely on `query`. Plus there is an additional issue for GET  requests, which I mentioned here.

2022-04-18 11:34 UTC, MiSikora commented
> **Known Issues** Couldn't successfully run the sample until i commented this part of the code
> 
> ```
> //        StrictMode.setVmPolicy(
> //            StrictMode.VmPolicy.Builder()
> //                .detectLeakedClosableObjects()
> //                .penaltyLog()
> //                .penaltyDeath()
> //                .build()
> //        )
> //
> //        StrictMode.setThreadPolicy(
> //            StrictMode.ThreadPolicy.Builder()
> //                .detectDiskReads()
> //                .detectDiskWrites()
> //                .penaltyLog()
> //                .penaltyDeath()
> //                .build()
> //        )
> ```

I experienced it in the past as well but I thought that #750 fixed it.

2022-05-02 20:24 UTC, cortinico commented
Sorry for the late reply here.
I've noticed we do have another similar PR here: #805
I'd like to understand which of the two we prefer to move forward.

2022-05-05 06:28 UTC, alkber commented
Please close this PR in respect of a better implementation at [https://github.com/ChuckerTeam/chucker/pull/805](url)

2022-05-06 15:39 UTC, cortinico commented
> Please close this PR in respect of a better implementation at [https://github.com/ChuckerTeam/chucker/pull/805](url)

👍 We'll keep the disucssion going on #805

2022-05-06 15:39 UTC, closed without merging