Filter transaction based graphql operation name
ChuckerTeam/chucker pull request #920
Opened 2022-11-08 14:56 UTC by ArjanSM

## :camera: Screenshots

<img src="https://user-images.githubusercontent.com/97124666/200592914-56e69493-6461-4eb7-ba03-dfb8a0818810.gif" width="300" height="550"/>

## :page_facing_up: Context

[issue#847](https://github.com/ChuckerTeam/chucker/issues/847)
## :pencil: Changes

1. Added a clause to the `getFilteredTuples` in the `HttpTransactionDao.kt` which enables filtering on the basis of `GraphQLOperationName`.  
In order to avoid any breaking changes the `pathQuery` argument is utilized to filter on the basis of `graphQLOperationName`.
I'm wondering if the argument name could be renamed to `filterQuery`? 
2. Tests in `HttpTransactionDatabaseRepositoryTest.kt` & `HttpTransactionDaoTest.kt` have been updated
## :paperclip: Related PR

🚫 
## :no_entry_sign: Breaking

🚫 
## :hammer_and_wrench: How to test

1. Launch Chucker Sample.
2. Click on `DO HTTP ACTIVITY` & `DO GRAPHQL ACTIVITY`
3. Click `LAUNCH CHUCKER ACTIVITY`
4. Click on the Search icon. And type "sea"
Chucker should filter the transactions and display a GraphQL transaction with the operation name as `SearchCharacters`
## :stopwatch: Next steps

2022-11-16 15:06 UTC, ArjanSM commented
@cortinico Apologies if you're busy! Any idea when would you be able to review this PR?

2022-11-18 14:52 UTC, cortinico commented
> @cortinico Apologies if you're busy! Any idea when would you be able to review this PR?

I'll look into this over the weekend/next week 👍

2022-11-26 22:37 UTC, cortinico requested changes
Thanks for sending this PR @ArjanSM 
There are a couple of bits to fix and then we can merge it 👍

2022-11-26 22:37 UTC, cortinico commented on library/src/main/kotlin/com/chuckerteam/chucker/internal/data/room/HttpTransactionDao.kt
>      fun getFilteredTuples(codeQuery: String, pathQuery: String): LiveData<List<HttpTransactionTuple>>
```suggestion
    fun getFilteredTuples(codeQuery: String, pathQuery: String, graphQlQuery: String = ""): LiveData<List<HttpTransactionTuple>>
```

2022-11-26 22:37 UTC, cortinico commented on library/src/main/kotlin/com/chuckerteam/chucker/internal/data/room/HttpTransactionDao.kt
>      fun getFilteredTuples(codeQuery: String, pathQuery: String): LiveData<List<HttpTransactionTuple>>
And at the call site please pass the same parameter twice, mentioning why.

Please also consider the empty case ("")

2022-11-26 22:37 UTC, cortinico commented on library/src/test/kotlin/com/chuckerteam/chucker/internal/data/repository/HttpTransactionDatabaseRepositoryTest.kt
> +        val transactionFour =
This should be in a separate test:

fun `transaction tuples are filtered by qraphQlOperationName`

2022-11-26 22:37 UTC, cortinico commented on library/src/test/kotlin/com/chuckerteam/chucker/internal/data/room/HttpTransactionDaoTest.kt
> +        val transactionFour =
Same as above

2022-11-26 22:37 UTC, cortinico commented on library/src/test/kotlin/com/chuckerteam/chucker/internal/data/repository/HttpTransactionDatabaseRepositoryTest.kt
> +            assertTuples(listOf(transactionFour,transactionThree, transactionTwo), result)
```suggestion
            assertTuples(listOf(transactionFour, transactionThree, transactionTwo), result)
```

2022-11-26 22:37 UTC, cortinico commented on library/src/test/kotlin/com/chuckerteam/chucker/internal/data/repository/HttpTransactionDatabaseRepositoryTest.kt
> +            assertTuples(listOf(transactionFour,transactionThree, transactionTwo), result)
Also it's suspicious that KtLint hasn't flagged this 🤔

2022-12-02 10:29 UTC, cortinico approved these changes
Let's add a small comment and is good to go for me 👍

2022-12-02 10:29 UTC, cortinico commented on library/src/main/kotlin/com/chuckerteam/chucker/internal/data/repository/HttpTransactionDatabaseRepository.kt
> +        )
Yes please 🙏

2022-12-07 09:33 UTC, vbuberen approved these changes
Looks good to me as well. Thanks a lot for your contributions with GraphQL stuff!

2022-12-08 10:45 UTC, merged